//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceDemoThreeConsoleClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.IService1", CallbackContract=typeof(WcfServiceDemoThreeConsoleClient.ServiceReference1.IService1Callback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:IService1/SendToServer")]
        void SendToServer(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:IService1/SendToServer")]
        System.Threading.Tasks.Task SendToServerAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:IService1/SendToServer2")]
        void SendToServer2(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:IService1/SendToServer2")]
        System.Threading.Tasks.Task SendToServer2Async(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:IService1/SendToClient")]
        void SendToClient(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfServiceDemoThreeConsoleClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.DuplexClientBase<WcfServiceDemoThreeConsoleClient.ServiceReference1.IService1>, WcfServiceDemoThreeConsoleClient.ServiceReference1.IService1 {
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SendToServer(int value) {
            base.Channel.SendToServer(value);
        }
        
        public System.Threading.Tasks.Task SendToServerAsync(int value) {
            return base.Channel.SendToServerAsync(value);
        }
        
        public void SendToServer2(int value) {
            base.Channel.SendToServer2(value);
        }
        
        public System.Threading.Tasks.Task SendToServer2Async(int value) {
            return base.Channel.SendToServer2Async(value);
        }
    }
}
